language: csharp
mono: none
solution: GoDaddyDotNet.sln 

dotnet: 2.1

install:
 - dotnet restore
 
script:
 - dotnet build
 - dotnet test GoDaddyDotNet.IntegrationTests/GoDaddyDotNet.IntegrationTests.csproj
 - dotnet pack GoDaddyDotNet/GoDaddyDotNet.csproj --output GoDaddyDotNet
 - dotnet nuget push GoDaddyDotNet/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org 